name: PHPUnit for Hyperf

on: [push, pull_request]

env:
  SW_VERSION: '4.5.9'

jobs:
  ci:
    name: Test on PHP${{ matrix.php-version }} Mysql${{ matrix.mysql-version }}
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['7.2', '7.3', '7.4']
        mysql-version: ['5.7', '8.0']
      max-parallel: 6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          extensions: redis
          ini-values: extension=swoole, opcache.enable_cli=1, swoole.use_shortname='Off'
          coverage: none
      - name: Setup Swoole
        run: |
          wget https://github.com/swoole/swoole-src/archive/v${SW_VERSION}.tar.gz -O swoole.tar.gz
          mkdir -p swoole
          tar -xf swoole.tar.gz -C swoole --strip-components=1
          rm swoole.tar.gz
          cd swoole
          phpize
          ./configure --enable-openssl --enable-mysqlnd --enable-http2
          make -j$(nproc)
          sudo make install
      - name: Setup Services
        run: |
          docker run --name mysql -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=true -d mysql:${{ matrix.mysql-version }} --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password
          docker run --name redis -p 6379:6379 -d redis
          docker run -d --name dev-consul -e CONSUL_BIND_INTERFACE=eth0 -p 8500:8500 consul
          docker run --name nsq -p 4150:4150 -p 4151:4151 -p 4160:4160 -p 4161:4161 -p 4170:4170 -p 4171:4171 --entrypoint /bin/nsqd -d nsqio/nsq:latest
          docker run -d --restart=always --name rabbitmq -p 4369:4369 -p 5672:5672 -p 15672:15672 -p 25672:25672 rabbitmq:management-alpine
      - name: Setp Mysql
        run: export TRAVIS_BUILD_DIR=$(pwd) && bash ./.travis/setup.mysql.sh
      - name: Setup Packages
        run: composer update -o
      - name: Setup Environment
        run: cp .env.example .env
      - name: Run Server
        run: |
          php bin/hyperf.php
          php bin/hyperf.php start &
      - name: Run Test Cases
        run: composer test
